#+TITLE: Emacs配置信息
#+AUTHOR: Ayanami
#+DATE: 2026/02/24
#+STARTUP: overview

* early-init.el
:PROPERTIES:
:HEADER-ARGS: :tangle early-init.el
:END:

在Emacs刚启动，还未加载主要配置文件时的配置文件。

#+BEGIN_SRC emacs-lisp
  ;;; early-init.el --- Emacs pre-initialization config -*- lexical-binding: t -*-
  ;;; Commentary:

  ;;; Code:

  ;; 设置垃圾回收参数
  (setq gc-cons-threshold most-positive-fixnum)
  (setq gc-cons-percentage 0.6)

  ;; 启动早期不加载`package.el'包管理器
  (setq package-enable-at-startup nil)
  ;; 不从包缓存中加载
  (setq package-quickstart nil)

  ;; 禁止展示菜单栏、工具栏和纵向滚动条
  (push '(menu-bar-lines . 0) default-frame-alist)
  (push '(tool-bar-lines . 0) default-frame-alist)
  (push '(vertical-scroll-bars) default-frame-alist)

  ;; 禁止自动缩放窗口先
  (setq frame-inhibit-implied-resize t)

  ;; 禁止菜单栏、工具栏、滚动条模式，禁止启动屏幕和文件对话框
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq inhibit-splash-screen t)
  (setq use-file-dialog nil)

  ;; 开机全屏
  (add-hook 'window-setup-hook #'toggle-frame-maximized t)
  ;;(add-to-list 'default-frame-alist '(fullscreen . fullboth))

  ;; 在这个阶段不编译
  (setq comp-deferred-compilation nil)

  (provide 'early-init)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; early-init.el ends here
#+END_SRC

* init.el
:PROPERTIES:
:HEADER-ARGS: :tangle init.el
:END:

=init.el= 是Emacs的主要配置文件。

** init.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init.el --- The main init entry for Emacs -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** package包管理配置
#+begin_src emacs-lisp
(require 'package)
(setq package-archives
	  '(("melpa"  . "https://melpa.org/packages/")
	    ("gnu"    . "https://elpa.gnu.org/packages/")
	    ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

(package-initialize)
#+end_src

** 安装use-package插件
[[https://github.com/jwiegley/use-package][use-package]] 是一个让Emacs配置更加结构化更加清晰的一个宏插件。

#+begin_src emacs-lisp
;; 安装 `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; 配置 `use-package'
(eval-and-compile
  (setq use-package-always-ensure nil)
  (setq use-package-always-defer nil)
  (setq use-package-expand-minimally nil)
  (setq use-package-enable-imenu-support t)
  (if (daemonp)
	  (setq use-package-always-demand t)))

(eval-when-compile
  (require 'use-package))

;; 安装 `use-package' 的集成模块
(use-package diminish
  :ensure t)
(use-package bind-key
  :ensure t)
#+end_src

** quelpa包管理器
[[https://github.com/quelpa/quelpa][quelpa]] 是配合 =package.el= 使用的，基于git的一个包管理器。
#+BEGIN_SRC emacs-lisp
;; 安装 `quelpa'
(use-package quelpa
  :ensure t
  :commands quelpa
  :config
  :custom
  (quelpa-git-clone-depth 1)
  (quelpa-update-melpa-p nil)
  (quelpa-self-upgrade-p nil)
  (quelpa-checkout-melpa-p nil))

;; `quelpa' 与 `use-package' 集成
(use-package quelpa-use-package
  :ensure t)
#+END_SRC
** 加载模块化配置
#+BEGIN_SRC emacs-lisp
  ;; 将lisp目录放到加载路径的前面以加快启动速度
  (let ((dir (locate-user-emacs-file "lisp")))
    (add-to-list 'load-path (file-name-as-directory dir)))

  ;; 加载各模块化配置
  ;; 不要在`*message*'缓冲区显示加载模块化配置的信息
  (with-temp-message ""
    (require 'init-ui)                    ; 加载UI交互的模块化配置文件
    (require 'init-edit)                  ; 加载编辑相关的配置
    (require 'init-org)                   ; 加载org相关的配置
    (require 'init-completion)            ; 加载自动补全相关的配置
    (require 'init-git)                   ; 加载magit相关的配置
    )
#+END_SRC
** init.el 文件尾
#+BEGIN_SRC emacs-lisp

(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))

(provide 'init)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init.el ends here
#+END_SRC

* init-ui.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-ui.el :mkdirp yes
:END:
** init-ui.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-ui.el --- UI settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC
** ef主题
#+BEGIN_SRC emacs-lisp
(use-package ef-themes
  :ensure t
  :bind ("C-c t" . ef-themes-toggle)
  :init
  ;; set two specific themes and switch between them
  (setq modus-themes-to-toggle '(ef-summer ef-winter))
  ;; set org headings and function syntax
  (setq modus-themes-headings
        '((0 . (bold 1))
          (1 . (bold 1))
          (2 . (rainbow bold 1))
          (3 . (rainbow bold 1))
          (4 . (rainbow bold 1))
          (t . (rainbow bold 1))))
  (setq ef-themes-region '(intense no-extend neutral))
  ;; Disable all other themes to avoid awkward blending:
  (mapc #'disable-theme custom-enabled-themes)

  ;; Load the theme of choice:
  ;; The themes we provide are recorded in the `ef-themes-dark-themes',
  ;; `ef-themes-light-themes'.

  ;; 如果你不喜欢随机主题，也可以直接固定选择一个主题，如下：
  ;;(ef-themes-select 'ef-dream)

  ;; 随机挑选一款主题，如果是命令行打开Emacs，则随机挑选一款黑色主题
  (if (display-graphic-p)
      (ef-themes-load-random)
    (ef-themes-load-random 'dark))

  :config
  ;; auto change theme, aligning with system themes.
  (defun my/apply-theme (appearance)
    "Load theme, taking current system APPEARANCE into consideration."
    (mapc #'disable-theme custom-enabled-themes)
    (pcase appearance
      ('light (if (display-graphic-p) (ef-themes-load-random 'light) (ef-themes-load-random 'dark)))
      ('dark (ef-themes-load-random 'dark))))

  (if (eq system-type 'darwin)
      ;; only for emacs-plus
      (add-hook 'ns-system-appearance-change-functions #'my/apply-theme)
    (ef-themes-select 'ef-summer)
    )
  )
#+END_SRC
** 字体设置
[[https://protesilaos.com/emacs/fontaine][fontaine]] 插件可以根据需要高度定制字体。
#+BEGIN_QUOTE
这篇文章可以作为字体设置的参考：
[[http://xahlee.info/emacs/emacs/emacs_list_and_set_font.html]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(use-package fontaine
  :ensure t
  :when (display-graphic-p)
  ;; :hook (kill-emacs . fontaine-store-latest-preset)
  :config
  (setq fontaine-latest-state-file
        (locate-user-emacs-file "etc/fontaine-latest-state.eld"))
  (setq fontaine-presets
        '((regular
           :default-height 140
           :default-weight regular
           :fixed-pitch-height 1.0
           :variable-pitch-height 1.0
           )
          (large
           :default-height 180
           :default-weight normal
           :fixed-pitch-height 1.0
           :variable-pitch-height 1.05
           )
          (t
           :default-family "Source Code Pro"
           :fixed-pitch-family "Source Code Pro"
           :variable-pitch-family "Source Code Pro"
           :italic-family "Source Code Pro"
           :variable-pitch-weight normal
           :bold-weight normal
           :italic-slant italic
           :line-spacing 0.1)
          ))
  ;; (fontaine-set-preset (or (fontaine-restore-latest-preset) 'regular))
  (fontaine-set-preset 'regular)

  ;; set emoji font
  (set-fontset-font
   t
   (if (version< emacs-version "28.1")
       '(#x1f300 . #x1fad0)
     'emoji)
   (cond
    ((member "Noto Emoji" (font-family-list)) "Noto Emoji")
    ((member "Symbola" (font-family-list)) "Symbola")
    ((member "Apple Color Emoji" (font-family-list)) "Apple Color Emoji")
    ((member "Noto Color Emoji" (font-family-list)) "Noto Color Emoji")
    ((member "Segoe UI Emoji" (font-family-list)) "Segoe UI Emoji")
    ))

  ;; set Chinese font
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :family
                (cond
                 ((eq system-type 'darwin)
                  (cond
                   ((member "Sarasa Mono SC Nerd" (font-family-list)) "Sarasa Mono SC Nerd")
                   ((member "PingFang SC" (font-family-list)) "PingFang SC")
                   ((member "WenQuanYi Zen Hei" (font-family-list)) "WenQuanYi Zen Hei")
                   ((member "Microsoft YaHei" (font-family-list)) "Microsoft YaHei")
                   ))
                 ((eq system-type 'gnu/linux)
                  (cond
                   ((member "Sarasa Mono SC Nerd" (font-family-list)) "Sarasa Mono SC Nerd")
                   ((member "WenQuanYi Micro Hei" (font-family-list)) "WenQuanYi Micro Hei")
                   ((member "WenQuanYi Zen Hei" (font-family-list)) "WenQuanYi Zen Hei")
                   ((member "Microsoft YaHei" (font-family-list)) "Microsoft YaHei")
                   ))
                 (t
                  (cond
                   ((member "Sarasa Mono SC Nerd" (font-family-list)) "Sarasa Mono SC Nerd")
                   ((member "Microsoft YaHei" (font-family-list)) "Microsoft YaHei")
                   )))
                )))

  ;; set Chinese font scale
  (setq face-font-rescale-alist `(
                                  ("Symbola"             . 1.3)
                                  ("Microsoft YaHei"     . 1.2)
                                  ("WenQuanYi Zen Hei"   . 1.2)
                                  ("Sarasa Mono SC Nerd" . 1.2)
                                  ("PingFang SC"         . 1.16)
                                  ("Lantinghei SC"       . 1.16)
                                  ("Kaiti SC"            . 1.16)
                                  ("Yuanti SC"           . 1.16)
                                  ("Apple Color Emoji"   . 0.91)
                                  ))
  )
#+END_SRC

#+CAPTION: 测试中英文字体对齐
#+NAME: 测试中英文字体对齐
| 中文  |   |
| abcd |   |
** 调整启动窗口大小

#+BEGIN_SRC emacs-lisp
;; 设置窗口大小，仅仅在图形界面需要设置
(when (display-graphic-p)
  (let ((top    0)                                     ; 顶不留空
        (left   (/ (x-display-pixel-width) 10))        ; 左边空10%
        (height (round (* 0.8                          ; 窗体高度为0.8倍的显示高度
                          (/ (x-display-pixel-height)
                             (frame-char-height))))))
    (let ((width  (round (* 2.5 height))))             ; 窗体宽度为2.5倍高度
      (setq default-frame-alist nil)
      (add-to-list 'default-frame-alist (cons 'top top))
      (add-to-list 'default-frame-alist (cons 'left left))
      (add-to-list 'default-frame-alist (cons 'height height))
      (add-to-list 'default-frame-alist (cons 'width width)))))
#+END_SRC
** 其他UI零散设置项

#+begin_src emacs-lisp
;; 禁用一些GUI特性
(setq use-dialog-box nil)               ; 鼠标操作不使用对话框
(setq inhibit-default-init t)           ; 不加载 `default' 库
(setq inhibit-startup-screen t)         ; 不加载启动画面
(setq inhibit-startup-message t)        ; 不加载启动消息
(setq inhibit-startup-buffer-menu t)    ; 不显示缓冲区列表

;; 草稿缓冲区默认文字设置
(setq initial-scratch-message (concat ";; Happy hacking, "
                                      (capitalize user-login-name) " - Emacs ♥ you!\n\n"))

;; 设置缓冲区的文字方向为从左到右
(setq bidi-paragraph-direction 'left-to-right)
;; 禁止使用双向括号算法
;; (setq bidi-inhibit-bpa t)

;; 设置自动折行宽度为80个字符，默认值为70
(setq-default fill-column 80)

;; 设置大文件阈值为100MB，默认10MB
(setq large-file-warning-threshold 100000000)

;; 以16进制显示字节数
(setq display-raw-bytes-as-hex t)
;; 有输入时禁止 `fontification' 相关的函数钩子，能让滚动更顺滑
(setq redisplay-skip-fontification-on-input t)

;; 禁止响铃
(setq ring-bell-function 'ignore)

;; 禁止闪烁光标
(blink-cursor-mode -1)

;; 在光标处而非鼠标所在位置粘贴
(setq mouse-yank-at-point t)

;; 拷贝粘贴设置
(setq select-enable-primary nil)        ; 选择文字时不拷贝
(setq select-enable-clipboard t)        ; 拷贝时使用剪贴板

;; 鼠标滚动设置
(setq scroll-step 2)
(setq scroll-margin 2)
(setq hscroll-step 2)
(setq hscroll-margin 2)
(setq scroll-conservatively 101)
(setq scroll-up-aggressively 0.01)
(setq scroll-down-aggressively 0.01)
(setq scroll-preserve-screen-position 'always)

;; 对于高的行禁止自动垂直滚动
(setq auto-window-vscroll nil)

;; 设置新分屏打开的位置的阈值
(setq split-width-threshold (assoc-default 'width default-frame-alist))
(setq split-height-threshold nil)

;; TAB键设置，在Emacs里不使用TAB键，所有的TAB默认为4个空格
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)

;; yes或no提示设置，通过下面这个函数设置当缓冲区名字匹配到预设的字符串时自动回答yes
(setq original-y-or-n-p 'y-or-n-p)
(defalias 'original-y-or-n-p (symbol-function 'y-or-n-p))
(defun default-yes-sometimes (prompt)
  "automatically say y when buffer name match following string"
  (if (or
	   (string-match "has a running process" prompt)
	   (string-match "does not exist; create" prompt)
	   (string-match "modified; kill anyway" prompt)
	   (string-match "Delete buffer using" prompt)
	   (string-match "Kill buffer of" prompt)
	   (string-match "still connected.  Kill it?" prompt)
	   (string-match "Shutdown the client's kernel" prompt)
	   (string-match "kill them and exit anyway" prompt)
	   (string-match "Revert buffer from file" prompt)
	   (string-match "Kill Dired buffer of" prompt)
	   (string-match "delete buffer using" prompt)
       (string-match "Kill all pass entry" prompt)
       (string-match "for all cursors" prompt)
	   (string-match "Do you want edit the entry" prompt))
	  t
    (original-y-or-n-p prompt)))
(defalias 'yes-or-no-p 'default-yes-sometimes)
(defalias 'y-or-n-p 'default-yes-sometimes)

;; 设置剪贴板历史长度300，默认为60
(setq kill-ring-max 200)

;; 在剪贴板里不存储重复内容
(setq kill-do-not-save-duplicates t)

;; 设置位置记录长度为6，默认为16
;; 可以使用 `counsel-mark-ring' or `consult-mark' (C-x j) 来访问光标位置记录
;; 使用 C-x C-SPC 执行 `pop-global-mark' 直接跳转到上一个全局位置处
;; 使用 C-u C-SPC 跳转到本地位置处
(setq mark-ring-max 6)
(setq global-mark-ring-max 6)

;; 设置 emacs-lisp 的限制
(setq max-lisp-eval-depth 10000)        ; 默认值为 800
(setq max-specpdl-size 10000)           ; 默认值为 1600

;; 启用 `list-timers', `list-threads' 这两个命令
(put 'list-timers 'disabled nil)
(put 'list-threads 'disabled nil)

;; 在命令行里支持鼠标
(xterm-mouse-mode 1)

;; 退出Emacs时进行确认
(setq confirm-kill-emacs 'y-or-n-p)

;; 在模式栏上显示当前光标的列号
(column-number-mode t)
#+end_src
** 编码设置

统一使用 UTF-8 编码。

#+begin_src emacs-lisp
;; 配置所有的编码为UTF-8，参考：
;; https://thraxys.wordpress.com/2016/01/13/utf-8-in-emacs-everywhere-forever/
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-language-environment 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(modify-coding-system-alist 'process "*" 'utf-8)
(when (display-graphic-p)
  (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)))
#+end_src
** 模式栏设置
*** doom-modeline插件

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] 是一个模式栏美化插件。

#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :hook (after-init . doom-modeline-mode)
  :custom
  (doom-modeline-irc nil)
  (doom-modeline-mu4e nil)
  (doom-modeline-gnus nil)
  (doom-modeline-github nil)
  (doom-modeline-buffer-file-name-style 'truncate-upto-root) ; : auto
  (doom-modeline-persp-name nil)
  (doom-modeline-unicode-fallback t)
  (doom-modeline-enable-word-count nil))
#+end_src

*** minions插件
[[https://github.com/tarsius/minions][minions]] 插件能让模式栏变得清爽，将次要模式隐藏起来。

#+BEGIN_SRC emacs-lisp
(use-package minions
  :ensure t
  :hook (after-init . minions-mode))
#+END_SRC
** keycast按键展示
[[https://github.com/tarsius/keycast][keycast mode]] 插件可以在模式栏上展示所有的按键，以及对应的函数。

#+BEGIN_SRC emacs-lisp
(use-package keycast
  :ensure t
  :hook (after-init . keycast-mode)
  ;; :custom-face
  ;; (keycast-key ((t (:background "#0030b4" :weight bold))))
  ;; (keycast-command ((t (:foreground "#0030b4" :weight bold))))
  :config
  ;; set for doom-modeline support
  ;; With the latest change 72d9add, mode-line-keycast needs to be modified to keycast-mode-line.
  (define-minor-mode keycast-mode
    "Show current command and its key binding in the mode line (fix for use with doom-mode-line)."
    :global t
    (if keycast-mode
        (progn
          (add-hook 'pre-command-hook 'keycast--update t)
          (add-to-list 'global-mode-string '("" keycast-mode-line "  ")))
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (delete '("" keycast-mode-line "  ") global-mode-string))
      ))

  (dolist (input '(self-insert-command
                   org-self-insert-command))
    (add-to-list 'keycast-substitute-alist `(,input "." "Typing…")))

  (dolist (event '(mouse-event-p
                   mouse-movement-p
                   mwheel-scroll))
    (add-to-list 'keycast-substitute-alist `(,event nil)))

  (setq keycast-log-format "%-20K%C\n")
  (setq keycast-log-frame-alist
        '((minibuffer . nil)))
  (setq keycast-log-newest-first t)
  )
#+END_SRC
** init-ui.el 文件尾
#+BEGIN_SRC emacs-lisp

(provide 'init-ui)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-ui.el ends here
#+END_SRC
* init-edit.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-edit.el :mkdirp yes
:END:

** init-edit.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-edit.el --- Editing settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** Emacs备份设置

不使用Emacs的自动备份设置。

#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)                                  ; 不自动备份
(setq auto-save-default nil)                                  ; 不使用Emacs自带的自动保存
#+END_SRC

** 解除一些不常用的快捷键

将一些不常用的快捷键解除，防止误操作。

#+BEGIN_SRC emacs-lisp
;; 解除不常用的快捷键定义
(global-set-key (kbd "C-z") nil)
(global-set-key (kbd "s-q") nil)
(global-set-key (kbd "M-z") nil)
(global-set-key (kbd "M-m") nil)
(global-set-key (kbd "C-x C-z") nil)
(global-set-key [mouse-2] nil)
#+END_SRC

** delsel选择文本输入时直接替换

Emacs默认选择文本后直接输入，是不会直接删除所选择的文本进行替换的。通过内置的 =delsel= 插件来实现这个行为。

#+begin_src emacs-lisp
;; Directly modify when selecting text
(use-package delsel
  :ensure nil
  :hook (after-init . delete-selection-mode))
#+end_src

** 自动重载设置

当我们的文件发生了改变后，我们希望Emacs里打开的永远是最新的文件，这个时候，我们需要对自动重载进行设置，让我们的Emacs在文件发生改变的时候自动重载文件。

#+BEGIN_SRC emacs-lisp
(use-package autorevert
  :ensure nil
  :hook (after-init . global-auto-revert-mode)
  :bind ("s-u" . revert-buffer)
  :custom
  (auto-revert-interval 10)
  (auto-revert-avoid-polling t)
  (auto-revert-verbose nil)
  (auto-revert-remote-files t)
  (auto-revert-check-vc-info t)
  (global-auto-revert-non-file-buffers t))
#+END_SRC

** init-edit.el 文件尾

#+BEGIN_SRC emacs-lisp
;; (message "init-base configuration: %.2fs"
;;          (float-time (time-subtract (current-time) my/init-base-start-time)))

(provide 'init-edit)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-edit.el ends here
#+END_SRC

* init-org.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-org.el :mkdirp yes
:END:

** init-org.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-org.el --- Org mode settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** org-auto-tangle自动tangle设置

[[https://github.com/yilkalargaw/org-auto-tangle][org-auto-tangle]] 插件可以在Org mode下自动进行tangle。

#+BEGIN_SRC emacs-lisp
(use-package org-auto-tangle
  :ensure t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t)
  )
#+END_SRC

** org美化以及快捷键的配置相关的配置
#+BEGIN_SRC emacs-lisp
    (use-package org
      :ensure nil
      :mode ("\\.org\\'" . org-mode)
      :bind (("C-c a" . org-agenda) ;; 绑定相应的快捷键
             ("C-c x" . org-capture))
      :hook ((org-mode . visual-line-mode)
    		 (org-mode . my/org-prettify-symbols))
      :commands (org-find-exact-headline-in-buffer org-set-tags)
      :custom-face
      ;; 设置Org mode标题以及每级标题行的大小
      (org-document-title ((t (:height 1.75 :weight bold))))
      (org-level-1 ((t (:height 1.2 :weight bold))))
      (org-level-2 ((t (:height 1.15 :weight bold))))
      (org-level-3 ((t (:height 1.1 :weight bold))))
      (org-level-4 ((t (:height 1.05 :weight bold))))
      (org-level-5 ((t (:height 1.0 :weight bold))))
      (org-level-6 ((t (:height 1.0 :weight bold))))
      (org-level-7 ((t (:height 1.0 :weight bold))))
      (org-level-8 ((t (:height 1.0 :weight bold))))
      (org-level-9 ((t (:height 1.0 :weight bold))))
      ;; 设置代码块用上下边线包裹
      (org-block-begin-line ((t (:underline t :background unspecified))))
      (org-block-end-line ((t (:overline t :underline nil :background unspecified))))
      :config
      ;; ================================
      ;; 在org mode里美化字符串
      ;; ================================
      (defun my/org-prettify-symbols ()
    	(setq prettify-symbols-alist
    		  (mapcan (lambda (x) (list x (cons (upcase (car x)) (cdr x))))
    				  '(
    					;; ("[ ]"              . 9744)         ; ☐
    					;; ("[X]"              . 9745)         ; ☑
    					;; ("[-]"              . 8863)         ; ⊟
    					("#+begin_src"      . 9998)         ; ✎
    					("#+end_src"        . 9633)         ; □
    					("#+begin_example"  . 129083)       ; 🠻
    					("#+end_example"    . 129081)       ; 🠹
    					("#+results:"       . 9776)         ; ☰
    					("#+attr_latex:"    . "🄛")
    					("#+attr_html:"     . "🄗")
    					("#+attr_org:"      . "🄞")
    					("#+name:"          . "🄝")         ; 127261
    					("#+caption:"       . "🄒")         ; 127250
    					("#+date:"          . "📅")         ; 128197
    					("#+author:"        . "💁")         ; 128100
    					("#+setupfile:"     . 128221)       ; 📝
    					("#+email:"         . 128231)       ; 📧
    					("#+startup:"       . 10034)        ; ✲
    					("#+options:"       . 9965)         ; ⛭
    					("#+title:"         . 10162)        ; ➲
    					("#+subtitle:"      . 11146)        ; ⮊
    					("#+downloaded:"    . 8650)         ; ⇊
    					("#+language:"      . 128441)       ; 🖹
    					("#+begin_quote"    . 187)          ; »
    					("#+end_quote"      . 171)          ; «
                        ("#+begin_results"  . 8943)         ; ⋯
                        ("#+end_results"    . 8943)         ; ⋯
    					)))
        (setq prettify-symbols-unprettify-at-point t)
    	(prettify-symbols-mode 1))

      ;; 提升latex预览的图片清晰度
      (plist-put org-format-latex-options :scale 1.8)

      ;; 设置标题行之间总是有空格；列表之间根据情况自动加空格
      (setq org-blank-before-new-entry '((heading . t)
    									 (plain-list-item . auto)
    									 ))

      ;; ======================================
      ;; 设置打开Org links的程序
      ;; ======================================
      (defun my-func/open-and-play-gif-image (file &optional link)
    	"Open and play GIF image `FILE' in Emacs buffer.

    Optional for Org-mode file: `LINK'."
    	(let ((gif-image (create-image file))
    		  (tmp-buf (get-buffer-create "*Org-mode GIF image animation*")))
    	  (switch-to-buffer tmp-buf)
    	  (erase-buffer)
    	  (insert-image gif-image)
    	  (image-animate gif-image nil t)
    	  (local-set-key (kbd "q") 'bury-buffer)
    	  ))
      (setq org-file-apps '(("\\.png\\'"     . default)
                            (auto-mode       . emacs)
                            (directory       . emacs)
                            ("\\.mm\\'"      . default)
                            ("\\.x?html?\\'" . default)
                            ("\\.pdf\\'"     . emacs)
                            ("\\.md\\'"      . emacs)
                            ("\\.gif\\'"     . my-func/open-and-play-gif-image)
                            ("\\.xlsx\\'"    . default)
                            ("\\.svg\\'"     . default)
                            ("\\.pptx\\'"    . default)
                            ("\\.docx\\'"    . default)))

      :custom
      ;; 设置Org mode的目录
      (org-directory "~/org")
      ;; 设置笔记的默认存储位置
      (org-default-notes-file (expand-file-name "capture.org" org-directory))
      ;; 启用一些子模块
      (org-modules '(ol-bibtex ol-gnus ol-info ol-eww org-habit org-protocol))
      ;; 在按M-RET时，是否根据光标所在的位置分行，这里设置为是
      ;; (org-M-RET-may-split-line '((default . nil)))
      ;; 一些Org mode自带的美化设置
      ;; 标题行美化
      (org-fontify-whole-heading-line t)
      ;; 设置标题行折叠符号
      (org-ellipsis " ▾")
      ;; 在活动区域内的所有标题栏执行某些命令
      (org-loop-over-headlines-in-active-region t)
      ;; TODO标签美化
      (org-fontify-todo-headline t)
      ;; DONE标签美化
      (org-fontify-done-headline t)
      ;; 引用块美化
      (org-fontify-quote-and-verse-blocks t)
      ;; 隐藏宏标记
      (org-hide-macro-markers t)
      ;; 隐藏强调标签
      (org-hide-emphasis-markers t)
      ;; 高亮latex语法
      (org-highlight-latex-and-related '(native script entities))
      ;; 以UTF-8显示
      (org-pretty-entities t)
      ;; 是否隐藏标题栏的前置星号，这里我们通过org-modern来隐藏
      ;; (org-hide-leading-stars t)
      ;; 当启用缩进模式时自动隐藏前置星号
      (org-indent-mode-turns-on-hiding-stars t)
      ;; 自动启用缩进
      (org-startup-indented nil)
      ;; 根据标题栏自动缩进文本
      (org-adapt-indentation nil)
      ;; 自动显示图片
      (org-startup-with-inline-images t)
      ;; 默认以Overview的模式展示标题行
      (org-startup-folded 'overview)
      ;; 允许字母列表
      (org-list-allow-alphabetical t)
      ;; 列表的下一级设置
      (org-list-demote-modify-bullet '(
    								   ("-"  . "+")
                                       ("+"  . "1.")
    								   ("1." . "a.")
    								   ))
      ;; 编辑时检查是否在折叠的不可见区域
      (org-fold-catch-invisible-edits 'smart)
      ;; 在当前位置插入新标题行还是在当前标题行后插入，这里设置为当前位置
      (org-insert-heading-respect-content nil)
      ;; 设置图片的最大宽度，如果有imagemagick支持将会改变图片实际宽度
      ;; 四种设置方法：(1080), 1080, t, nil
      (org-image-actual-width nil)
      ;; imenu的最大深度，默认为2
      (org-imenu-depth 4)
      ;; 回车要不要触发链接，这里设置不触发
      (org-return-follows-link nil)
      ;; 上标^下标_是否需要特殊字符包裹，这里设置需要用大括号包裹
      (org-use-sub-superscripts '{})
      ;; 复制粘贴标题行的时候删除id
      (org-clone-delete-id t)
      ;; 粘贴时调整标题行的级别
      (org-yank-adjusted-subtrees t)

      ;; TOOD的关键词设置，可以设置不同的组
      (org-todo-keywords '((sequence "TODO(t)" "HOLD(h!)" "WIP(i!)" "WAIT(w!)" "|" "DONE(d!)" "CANCELLED(c@/!)")
    					   (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f!)")))
      ;; TODO关键词的样式设置
      (org-todo-keyword-faces '(("TODO"       :foreground "#7c7c75" :weight bold)
    							("HOLD"       :foreground "#feb24c" :weight bold)
    							("WIP"        :foreground "#0098dd" :weight bold)
    							("WAIT"       :foreground "#9f7efe" :weight bold)
    							("DONE"       :foreground "#50a14f" :weight bold)
    							("CANCELLED"  :foreground "#ff6480" :weight bold)
    							("REPORT"     :foreground "magenta" :weight bold)
    							("BUG"        :foreground "red"     :weight bold)
    							("KNOWNCAUSE" :foreground "yellow"  :weight bold)
    							("FIXED"      :foreground "green"   :weight bold)))
      ;; 当标题行状态变化时标签同步发生的变化
      ;; Moving a task to CANCELLED adds a CANCELLED tag
      ;; Moving a task to WAIT adds a WAIT tag
      ;; Moving a task to HOLD adds WAIT and HOLD tags
      ;; Moving a task to a done state removes WAIT and HOLD tags
      ;; Moving a task to TODO removes WAIT, CANCELLED, and HOLD tags
      ;; Moving a task to DONE removes WAIT, CANCELLED, and HOLD tags
      (org-todo-state-tags-triggers
       (quote (("CANCELLED" ("CANCELLED" . t))
    		   ("WAIT" ("WAIT" . t))
    		   ("HOLD" ("WAIT") ("HOLD" . t))
    		   (done ("WAIT") ("HOLD"))
    		   ("TODO" ("WAIT") ("CANCELLED") ("HOLD"))
    		   ("DONE" ("WAIT") ("CANCELLED") ("HOLD")))))
      ;; 使用专家模式选择标题栏状态
      (org-use-fast-todo-selection 'expert)
      ;; 父子标题栏状态有依赖
      (org-enforce-todo-dependencies t)
      ;; 标题栏和任务复选框有依赖
      (org-enforce-todo-checkbox-dependencies t)
      ;; 优先级样式设置
      (org-priority-faces '((?A :foreground "red")
    						(?B :foreground "orange")
    						(?C :foreground "yellow")))
      ;; 标题行全局属性设置
      (org-global-properties '(("EFFORT_ALL" . "0:15 0:30 0:45 1:00 2:00 3:00 4:00 5:00 6:00 7:00 8:00")
    						   ("APPT_WARNTIME_ALL" . "0 5 10 15 20 25 30 45 60")
    						   ("RISK_ALL" . "Low Medium High")
    						   ("STYLE_ALL" . "habit")))
      ;; Org columns的默认格式
      (org-columns-default-format "%25ITEM %TODO %SCHEDULED %DEADLINE %3PRIORITY %TAGS %CLOCKSUM %EFFORT{:}")
      ;; 当状态从DONE改成其他状态时，移除 CLOSED: [timestamp]
      (org-closed-keep-when-no-todo t)
      ;; DONE时加上时间戳
      (org-log-done 'time)
      ;; 重复执行时加上时间戳
      (org-log-repeat 'time)
      ;; Deadline修改时加上一条记录
      (org-log-redeadline 'note)
      ;; Schedule修改时加上一条记录
      (org-log-reschedule 'note)
      ;; 以抽屉的方式记录
      (org-log-into-drawer t)
      ;; 紧接着标题行或者计划/截止时间戳后加上记录抽屉
      (org-log-state-notes-insert-after-drawers nil)

      ;; refile使用缓存
      (org-refile-use-cache t)
      ;; refile的目的地，这里设置的是agenda文件的所有标题
      (org-refile-targets '((org-agenda-files . (:maxlevel . 9))))
      ;; 将文件名加入到路径
      (org-refile-use-outline-path 'file)
      ;; 是否按步骤refile
      (org-outline-path-complete-in-steps nil)
      ;; 允许创建新的标题行，但需要确认
      (org-refile-allow-creating-parent-nodes 'confirm)

      ;; 设置标签的默认位置，默认是第77列右对齐
      ;; (org-tags-column -77)
      ;; 自动对齐标签
      (org-auto-align-tags t)
      ;; 标签不继承
      (org-use-tag-inheritance nil)
      ;; 在日程视图的标签不继承
      (org-agenda-use-tag-inheritance nil)
      ;; 标签快速选择
      (org-use-fast-tag-selection t)
      ;; 标签选择不需要回车确认
      (org-fast-tag-selection-single-key t)
      ;; 定义了有序属性的标题行也加上 OREDERD 标签
      (org-track-ordered-property-with-tag t)
      ;; 始终存在的的标签
      (org-tag-persistent-alist '(("read"     . ?r)
    							  ("mail"     . ?m)
    							  ("emacs"    . ?e)
    							  ("study"    . ?s)
    							  ("work"     . ?w)))
      ;; 预定义好的标签
      (org-tag-alist '((:startgroup)
    				   ("crypt"    . ?c)
    				   ("linux"    . ?l)
    				   ("apple"    . ?a)
    				   ("noexport" . ?n)
    				   ("ignore"   . ?i)
    				   ("TOC"      . ?t)
    				   (:endgroup)))

      ;; 归档设置
      (org-archive-location "%s_archive::datetree/")
      )

    ;; Org mode的附加包，有诸多附加功能
    (use-package org-contrib
      :ensure t)

  (use-package org-modern
    :ensure t
    :hook (after-init . (lambda ()
                          (setq org-modern-hide-stars 'leading)
                          (global-org-modern-mode t)))
    :config
    ;; 标题行型号字符
    (setq org-modern-star ["◉" "○" "✸" "✳" "◈" "◇" "✿" "❀" "✜"])
    ;; 额外的行间距，0.1表示10%，1表示1px
    (setq-default line-spacing 0.1)
    ;; tag边框宽度，还可以设置为 `auto' 即自动计算
    (setq org-modern-label-border 1)
    ;; 设置表格竖线宽度，默认为3
    (setq org-modern-table-vertical 2)
    ;; 设置表格横线为0，默认为0.1
    (setq org-modern-table-horizontal 0)
    ;; 复选框美化
    (setq org-modern-checkbox
          '((?X . #("▢✓" 0 2 (composition ((2)))))
            (?- . #("▢–" 0 2 (composition ((2)))))
            (?\s . #("▢" 0 1 (composition ((1)))))))
    ;; 列表符号美化
    (setq org-modern-list
          '((?- . "•")
            (?+ . "◦")
            (?* . "▹")))
    ;; 代码块左边加上一条竖边线（需要Org mode顶头，如果启用了 `visual-fill-column-mode' 会很难看）
    (setq org-modern-block-fringe t)
    ;; 代码块类型美化，我们使用了 `prettify-symbols-mode'
    (setq org-modern-block-name nil)
    ;; #+关键字美化，我们使用了 `prettify-symbols-mode'
    (setq org-modern-keyword nil)
    )
#+END_SRC

** org-capture模版的配置
#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates `(("t" "Tasks" entry (file+headline "tasks.org" "Reminders")
                                 "* TODO %i%?"
                            :empty-lines-after 1
                            :prepend t)
                           ("n" "Notes" entry (file+headline "notes.org" "Notes")
                            "* %? %^g\n%i\n"
                            :empty-lines-after 1)
                           ("i" "Inbox" entry (file+headline "inbox.org" "Inboxs")
                            "* %? %^g\n%i\n"
                            :empty-lines-after 1)                                                     
                           ;; For EWW
                           ("b" "Bookmarks" entry (file+headline "capture.org" "Bookmarks")
                            "* %:description\n\n%a%?"
                            :empty-lines 1
                            :immediate-finish t)
                           ("d" "Diary")
                           ("dt" "Today's TODO list" entry (file+olp+datetree "diary.org")
                            "* Today's TODO list [/]\n%T\n\n** TODO %?"
                            :empty-lines 1
                            :jump-to-captured t)
                           ("dw" "Today's work" entry (file+olp+datetree "diary-work.org")
                            "* %?\n%T\n\n%i"
                            :empty-lines 1
                            :jump-to-captured t)
                           ("do" "Other stuff" entry (file+olp+datetree "diary.org")
                            "* %?\n%T\n\n%i"
                            :empty-lines 1
                            :jump-to-captured t)
                           ))
#+END_SRC

** org-appear自动展开链接
#+BEGIN_SRC emacs-lisp
(use-package org-appear
  :ensure t
  :hook (org-mode . org-appear-mode)
  :config
  (setq org-appear-autolinks t)
  (setq org-appear-autosubmarkers t)
  (setq org-appear-autoentities t)
  (setq org-appear-autokeywords t)
  (setq org-appear-inside-latex t)
  )
#+END_SRC

** init-org.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-org)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-org.el ends here
#+END_SRC

* init-completion.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-completion.el :mkdirp yes
:END:

** init-completion.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-completion.el --- Org mode settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC
** vertico
#+BEGIN_SRC emacs-lisp
  (use-package vertico
  :ensure t
  :hook (after-init . vertico-mode)
  :bind (:map minibuffer-local-map
              ("M-<DEL>" . my/minibuffer-backward-kill)
              :map vertico-map
              ("M-q" . vertico-quick-insert)) ; use C-g to exit
  :config
  (defun my/minibuffer-backward-kill (arg)
    "When minibuffer is completing a file name delete up to parent
folder, otherwise delete a word"
    (interactive "p")
    (if minibuffer-completing-file-name
        ;; Borrowed from https://github.com/raxod502/selectrum/issues/498#issuecomment-803283608
        (if (string-match-p "/." (minibuffer-contents))
            (zap-up-to-char (- arg) ?/)
          (delete-minibuffer-contents))
      (backward-kill-word arg)))

  ;; Do not allow the cursor in the minibuffer prompt
  (setq minibuffer-prompt-properties
        '(read-only t cursor-intangible t face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)

  (setq vertico-cycle t)                ; cycle from last to first
  :custom
  (vertico-count 15)                    ; number of candidates to display, default is 10
  )
#+END_SRC
** orderless和pinyin
#+BEGIN_SRC emacs-lisp
  ;; support Pinyin first character match for orderless, avy etc.
(use-package pinyinlib
  :ensure t)

;; orderless 是一种哲学思想
(use-package orderless
  :ensure t
  :init
  (setq completion-styles '(orderless partial-completion basic))
  (setq orderless-component-separator "[ &]") ; & is for company because space will break completion
  (setq completion-category-defaults nil)
  (setq completion-category-overrides nil)
  :config
  ;; make completion support pinyin, refer to
  ;; https://emacs-china.org/t/vertico/17913/2
  (defun completion--regex-pinyin (str)
    (orderless-regexp (pinyinlib-build-regexp-string str)))
  (add-to-list 'orderless-matching-styles 'completion--regex-pinyin)
  )
#+END_SRC
** marginalia
#+BEGIN_SRC emacs-lisp
  (use-package marginalia
    :ensure t
    :hook (after-init . marginalia-mode))  
#+END_SRC
** consult
#+BEGIN_SRC emacs-lisp
  (use-package consult
  :ensure t
  :after org
  :bind (([remap goto-line]                     . consult-goto-line)
         ([remap isearch-forward]               . consult-line-symbol-at-point) ; my-consult-ripgrep-or-line
         ([remap switch-to-buffer]              . consult-buffer)
         ([remap switch-to-buffer-other-window] . consult-buffer-other-window)
         ([remap switch-to-buffer-other-frame]  . consult-buffer-other-frame)
         ([remap yank-pop]                      . consult-yank-pop)
         ([remap apropos]                       . consult-apropos)
         ([remap bookmark-jump]                 . consult-bookmark)
         ([remap goto-line]                     . consult-goto-line)
         ([remap imenu]                         . consult-imenu)
         ([remap multi-occur]                   . consult-multi-occur)
         ([remap recentf-open-files]            . consult-recent-file)
         ("C-x j"                               . consult-mark)
         ("C-c g"                               . consult-ripgrep)
         ("C-c f"                               . consult-find)
         ("\e\ef"                               . consult-locate) ; need to enable locate first
         ("C-c n h"                             . my/consult-find-org-headings)
         :map org-mode-map
         ("C-c C-j"                             . consult-org-heading)
         :map minibuffer-local-map
         ("C-r"                                 . consult-history)
         :map isearch-mode-map
         ("C-;"                                 . consult-line)
         :map prog-mode-map
         ("C-c C-j"                             . consult-outline)
         )
  :hook (completion-list-mode . consult-preview-at-point-mode)
  :init
  ;; Optionally configure the register formatting. This improves the register
  ;; preview for `consult-register', `consult-register-load',
  ;; `consult-register-store' and the Emacs built-ins.
  (setq register-preview-delay 0
        register-preview-function #'consult-register-format)

  ;; Optionally tweak the register preview window.
  ;; This adds thin lines, sorting and hides the mode line of the window.
  (advice-add #'register-preview :override #'consult-register-window)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)

  ;; MacOS locate doesn't support `--ignore-case --existing' args.
  (setq consult-locate-args (pcase system-type
                              ('gnu/linux "locate --ignore-case --existing --regex")
                              ('darwin "mdfind -name")))
  :config
  (consult-customize
   consult-theme
   :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep
   consult-bookmark consult-recent-file consult-xref
   :preview-key (kbd "M-."))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<") ;; (kbd "C-+")

  (autoload 'projectile-project-root "projectile")
  (setq consult-project-root-function #'projectile-project-root)

  ;; search all org file headings under a directory, see:
  ;; https://emacs-china.org/t/org-files-heading-entry/20830/4
  (defun my/consult-find-org-headings (&optional match)
    "find headngs in all org files."
    (interactive)
    (consult-org-heading match (directory-files org-directory t "^[0-9]\\{8\\}.+\\.org$")))

  ;; Use `consult-ripgrep' instead of `consult-line' in large buffers
  (defun consult-line-symbol-at-point ()
    "Consult line the synbol where the point is"
    (interactive)
    (consult-line (thing-at-point 'symbol)))
  )
#+END_SRC
** corfu
#+BEGIN_SRC emacs-lisp
(use-package corfu
  :ensure t
  :hook (after-init . global-corfu-mode)
  :bind
  (:map corfu-map
        ("SPC" . corfu-insert-separator)    ; configure space for separator insertion
        ("M-q" . corfu-quick-complete)      ; use C-g to exit
        ("TAB" . corfu-next)
        ([tab] . corfu-next)
        ("S-TAB" . corfu-previous)
        ([backtab] . corfu-previous))
  :config
  ;; TAB cycle if there are only few candidates
  (setq completion-cycle-threshold 0)
  (setq tab-always-indent 'complete)

  (defun corfu-enable-always-in-minibuffer ()
    "Enable Corfu in the minibuffer if Vertico/Mct are not active."
    (unless (or (bound-and-true-p mct--active)
                (bound-and-true-p vertico--input))
      ;; (setq-local corfu-auto nil) Enable/disable auto completion
      (corfu-mode 1)))
  (add-hook 'minibuffer-setup-hook #'corfu-enable-always-in-minibuffer 1)

  ;; enable corfu in eshell
  (add-hook 'eshell-mode-hook
            (lambda ()
              (setq-local corfu-auto nil)
              (corfu-mode)))

  ;; For Eshell
  ;; ===========
  ;; avoid press RET twice in Eshell
  (defun corfu-send-shell (&rest _)
    "Send completion candidate when inside comint/eshell."
    (cond
     ((and (derived-mode-p 'eshell-mode) (fboundp 'eshell-send-input))
      (eshell-send-input))
     ((and (derived-mode-p 'comint-mode)  (fboundp 'comint-send-input))
      (comint-send-input))))

  (advice-add #'corfu-insert :after #'corfu-send-shell)

  :custom
  (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  )
#+END_SRC
** cape
#+BEGIN_SRC emacs-lisp
  ;; Add extensions
  (use-package cape
    :ensure t
    :commands (cape-file cape-elisp-block cape-keyword)
    :autoload (cape-wrap-noninterruptible cape-wrap-nonexclusive cape-wrap-buster)
    :autoload (cape-wrap-silent)
    :init
    ;; (add-to-list 'completion-at-point-functions #'cape-dabbrev)
    (add-to-list 'completion-at-point-functions #'cape-file)
    (add-to-list 'completion-at-point-functions #'cape-elisp-block)
    (add-to-list 'completion-at-point-functions #'cape-keyword)
    ;; (add-to-list 'completion-at-point-functions #'cape-abbrev)

    ;; Make these capfs composable.
    (advice-add 'lsp-completion-at-point :around #'cape-wrap-noninterruptible)
    (advice-add 'lsp-completion-at-point :around #'cape-wrap-nonexclusive)
    (advice-add 'comint-completion-at-point :around #'cape-wrap-nonexclusive)
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster)
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-nonexclusive)
    (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-nonexclusive))
#+END_SRC

** yasnippet补全模版
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
  :ensure t
  :diminish yas-minor-mode
  :hook ((after-init . yas-reload-all)
         ((prog-mode LaTeX-mode org-mode) . yas-minor-mode))
  :config
  ;; Suppress warning for yasnippet code.
  (require 'warnings)
  (add-to-list 'warning-suppress-types '(yasnippet backquote-change))

  (setq yas-prompt-functions '(yas-x-prompt yas-dropdown-prompt))
  (defun smarter-yas-expand-next-field ()
    "Try to `yas-expand' then `yas-next-field' at current cursor position."
    (interactive)
    (let ((old-point (point))
          (old-tick (buffer-chars-modified-tick)))
      (yas-expand)
      (when (and (eq old-point (point))
                 (eq old-tick (buffer-chars-modified-tick)))
        (ignore-errors (yas-next-field))))))
  ;; 追加一些模版
  (use-package yasnippet-snippets
    :ensure t)
#+END_SRC
** init-completion.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-completion)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-org.el ends here
#+END_SRC

* init-git.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-git.el :mkdirp yes
:END:

** init-git 文件头
#+BEGIN_SRC emacs-lisp
  ;;; init-git.el --- Org mode settings -*- lexical-binding: t -*-
  ;;; Commentary:

  ;;; Code:
  #+END_SRC

** 配置magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :hook (git-commit-mode . flyspell-mode)
    :bind (("C-x g"   . magit-status)
           ("C-x M-g" . magit-dispatch)
           ("C-c M-g" . magit-file-dispatch))
    :custom
    (magit-diff-refine-hunk t)
    (magit-ediff-dwim-show-on-hunks t))
#+END_SRC

** 追加关于todo的显示
#+begin_src emacs-lisp
  ;; Show TODOs in Magit
  (use-package magit-todos
    :ensure t
    :after magit-status
    :commands magit-todos-mode
    :init
    (setq magit-todos-nice (if (executable-find "nice") t nil))
    (magit-todos-mode 1))
#+end_src
** 高亮显示修改部分内容
#+BEGIN_SRC emacs-lisp
  (use-package diff-hl
    :ensure t
    :hook ((dired-mode         . diff-hl-dired-mode-unless-remote)
           (magit-pre-refresh  . diff-hl-magit-pre-refresh)
           (magit-post-refresh . diff-hl-magit-post-refresh))
    :init
    (global-diff-hl-mode t)
    :config
    ;; When Emacs runs in terminal, show the indicators in margin instead.
    (unless (display-graphic-p)
      (diff-hl-margin-mode)))
#+END_SRC
** init-git 文件尾

#+BEGIN_SRC emacs-lisp

  (provide 'init-git)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; init-git.el ends here
  #+END_SRC
